using System;
using System.Collections.Generic;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414

public partial class DB_EquipItem : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_EquipItem(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_EquipItem(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4935134361176504373UL,4898986758966256573UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String f_name
	{
		get => _f_name[Index];
		set => _f_name[Index] = value;
	}
	public System.Int32 f_ID
	{
		get => _f_ID[Index];
		set => _f_ID[Index] = value;
	}
	public System.String f_Image
	{
		get => _f_Image[Index];
		set => _f_Image[Index] = value;
	}
	public System.String f_Name
	{
		get => _f_Name[Index];
		set => _f_Name[Index] = value;
	}
	public Inventory.Model.ItemSO.ItemType f_Type
	{
		get => (Inventory.Model.ItemSO.ItemType) _f_Type[Index];
		set => _f_Type[Index] = value;
	}
	public ColorPallete.ItemQuality f_Quality
	{
		get => (ColorPallete.ItemQuality) _f_Quality[Index];
		set => _f_Quality[Index] = value;
	}
	public System.String f_Description
	{
		get => _f_Description[Index];
		set => _f_Description[Index] = value;
	}
	public System.String f_Weapon
	{
		get => _f_Weapon[Index];
		set => _f_Weapon[Index] = value;
	}
	public List<DB_Parameters> f_Parameters => BGCodeGenUtils.GetNested<DB_Parameters>(_f_Parameters, Index);
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5731409113056981974UL, 3443103030951795646UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_f_ID;
	public static BansheeGz.BGDatabase.BGFieldInt _f_ID => _ufle12jhs77_f_ID ?? (_ufle12jhs77_f_ID = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5001392202063041672UL, 17344440309849545368UL), () => _ufle12jhs77_f_ID = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_Image;
	public static BansheeGz.BGDatabase.BGFieldString _f_Image => _ufle12jhs77_f_Image ?? (_ufle12jhs77_f_Image = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5574281017795830705UL, 3767862667206356878UL), () => _ufle12jhs77_f_Image = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_Name;
	public static BansheeGz.BGDatabase.BGFieldString _f_Name => _ufle12jhs77_f_Name ?? (_ufle12jhs77_f_Name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5073918912524671525UL, 10529315167146948794UL), () => _ufle12jhs77_f_Name = null));
	private static BansheeGz.BGDatabase.BGFieldEnum _ufle12jhs77_f_Type;
	public static BansheeGz.BGDatabase.BGFieldEnum _f_Type => _ufle12jhs77_f_Type ?? (_ufle12jhs77_f_Type = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEnum>(MetaDefault, new BGId(4886593411586595779UL, 7034789370122234788UL), () => _ufle12jhs77_f_Type = null));
	private static BansheeGz.BGDatabase.BGFieldEnum _ufle12jhs77_f_Quality;
	public static BansheeGz.BGDatabase.BGFieldEnum _f_Quality => _ufle12jhs77_f_Quality ?? (_ufle12jhs77_f_Quality = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEnum>(MetaDefault, new BGId(5490739581985317334UL, 13480717401404523156UL), () => _ufle12jhs77_f_Quality = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_Description;
	public static BansheeGz.BGDatabase.BGFieldString _f_Description => _ufle12jhs77_f_Description ?? (_ufle12jhs77_f_Description = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4847610943813721877UL, 15326442594951189891UL), () => _ufle12jhs77_f_Description = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_Weapon;
	public static BansheeGz.BGDatabase.BGFieldString _f_Weapon => _ufle12jhs77_f_Weapon ?? (_ufle12jhs77_f_Weapon = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5613036474891219760UL, 12897445845885008513UL), () => _ufle12jhs77_f_Weapon = null));
	private static BansheeGz.BGDatabase.BGFieldNested _ufle12jhs77_f_Parameters;
	public static BansheeGz.BGDatabase.BGFieldNested _f_Parameters => _ufle12jhs77_f_Parameters ?? (_ufle12jhs77_f_Parameters = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldNested>(MetaDefault, new BGId(4941600396802500167UL, 7633736066423875755UL), () => _ufle12jhs77_f_Parameters = null));
	private static readonly DB_EquipItem.Factory _factory0_PFS = new DB_EquipItem.Factory();
	private static readonly DB_Parameters.Factory _factory1_PFS = new DB_Parameters.Factory();
	private static readonly DB_ConsumeItem.Factory _factory2_PFS = new DB_ConsumeItem.Factory();
	private static readonly DB_Modifiers.Factory _factory3_PFS = new DB_Modifiers.Factory();
	private static readonly DB_UpgradeItem.Factory _factory4_PFS = new DB_UpgradeItem.Factory();
	private static readonly DB_UParameters.Factory _factory5_PFS = new DB_UParameters.Factory();
	private static readonly DB_BuffModifier.Factory _factory6_PFS = new DB_BuffModifier.Factory();
	private DB_EquipItem() : base(MetaDefault)
	{
	}
	private DB_EquipItem(BGId id) : base(MetaDefault, id)
	{
	}
	private DB_EquipItem(BGMetaEntity meta) : base(meta)
	{
	}
	private DB_EquipItem(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static DB_EquipItem FindEntity(Predicate<DB_EquipItem> filter)
	{
		return MetaDefault.FindEntity(entity => filter==null || filter((DB_EquipItem) entity)) as DB_EquipItem;
	}
	public static List<DB_EquipItem> FindEntities(Predicate<DB_EquipItem> filter, List<DB_EquipItem> result=null, Comparison<DB_EquipItem> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_EquipItem> action, Predicate<DB_EquipItem> filter=null, Comparison<DB_EquipItem> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((DB_EquipItem) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((DB_EquipItem) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((DB_EquipItem)e1,(DB_EquipItem)e2));
	}
	public static DB_EquipItem GetEntity(BGId entityId) => (DB_EquipItem) MetaDefault.GetEntity(entityId);
	public static DB_EquipItem GetEntity(int index) => (DB_EquipItem) MetaDefault[index];
	public static DB_EquipItem GetEntity(string entityName) => (DB_EquipItem) MetaDefault.GetEntity(entityName);
	public static DB_EquipItem NewEntity() => (DB_EquipItem) MetaDefault.NewEntity();
	public static DB_EquipItem NewEntity(BGId entityId) => (DB_EquipItem) MetaDefault.NewEntity(entityId);
	public static DB_EquipItem NewEntity(Action<DB_EquipItem> callback)
	{
		return (DB_EquipItem) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((DB_EquipItem)entity)));
	}
}

public partial class DB_Parameters : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_Parameters(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_Parameters(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaNested _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaNested MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaNested>(new BGId(4998874172023266660UL,14678023312362303876UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String f_name
	{
		get => _f_name[Index];
		set => _f_name[Index] = value;
	}
	public DB_EquipItem f_EquipItem
	{
		get => (DB_EquipItem) _f_EquipItem[Index];
		set => _f_EquipItem[Index] = value;
	}
	public System.String f_Parameter
	{
		get => _f_Parameter[Index];
		set => _f_Parameter[Index] = value;
	}
	public System.Single f_Value
	{
		get => _f_Value[Index];
		set => _f_Value[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4722463213798532221UL, 4285348532595993268UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_EquipItem;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_EquipItem => _ufle12jhs77_f_EquipItem ?? (_ufle12jhs77_f_EquipItem = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(4804280707245585370UL, 13129731919561917107UL), () => _ufle12jhs77_f_EquipItem = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_Parameter;
	public static BansheeGz.BGDatabase.BGFieldString _f_Parameter => _ufle12jhs77_f_Parameter ?? (_ufle12jhs77_f_Parameter = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5113264856237063357UL, 12378592823516549307UL), () => _ufle12jhs77_f_Parameter = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_f_Value;
	public static BansheeGz.BGDatabase.BGFieldFloat _f_Value => _ufle12jhs77_f_Value ?? (_ufle12jhs77_f_Value = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(4905587419478848161UL, 4383493197777814717UL), () => _ufle12jhs77_f_Value = null));
	private static readonly DB_EquipItem.Factory _factory0_PFS = new DB_EquipItem.Factory();
	private static readonly DB_Parameters.Factory _factory1_PFS = new DB_Parameters.Factory();
	private static readonly DB_ConsumeItem.Factory _factory2_PFS = new DB_ConsumeItem.Factory();
	private static readonly DB_Modifiers.Factory _factory3_PFS = new DB_Modifiers.Factory();
	private static readonly DB_UpgradeItem.Factory _factory4_PFS = new DB_UpgradeItem.Factory();
	private static readonly DB_UParameters.Factory _factory5_PFS = new DB_UParameters.Factory();
	private static readonly DB_BuffModifier.Factory _factory6_PFS = new DB_BuffModifier.Factory();
	private DB_Parameters() : base(MetaDefault)
	{
	}
	private DB_Parameters(BGId id) : base(MetaDefault, id)
	{
	}
	private DB_Parameters(BGMetaEntity meta) : base(meta)
	{
	}
	private DB_Parameters(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static DB_Parameters FindEntity(Predicate<DB_Parameters> filter)
	{
		return MetaDefault.FindEntity(entity => filter==null || filter((DB_Parameters) entity)) as DB_Parameters;
	}
	public static List<DB_Parameters> FindEntities(Predicate<DB_Parameters> filter, List<DB_Parameters> result=null, Comparison<DB_Parameters> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_Parameters> action, Predicate<DB_Parameters> filter=null, Comparison<DB_Parameters> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((DB_Parameters) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((DB_Parameters) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((DB_Parameters)e1,(DB_Parameters)e2));
	}
	public static DB_Parameters GetEntity(BGId entityId) => (DB_Parameters) MetaDefault.GetEntity(entityId);
	public static DB_Parameters GetEntity(int index) => (DB_Parameters) MetaDefault[index];
	public static DB_Parameters GetEntity(string entityName) => (DB_Parameters) MetaDefault.GetEntity(entityName);
	public static DB_Parameters NewEntity() => (DB_Parameters) MetaDefault.NewEntity();
	public static DB_Parameters NewEntity(BGId entityId) => (DB_Parameters) MetaDefault.NewEntity(entityId);
	public static DB_Parameters NewEntity(Action<DB_Parameters> callback)
	{
		return (DB_Parameters) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((DB_Parameters)entity)));
	}
	public static DB_Parameters NewEntity(DB_EquipItem owner) => (DB_Parameters) MetaDefault.NewEntity(owner);
	public static DB_Parameters NewEntity(DB_EquipItem owner, BGId entityId) => (DB_Parameters) MetaDefault.NewEntity(owner, entityId);
	public static DB_Parameters NewEntity(DB_EquipItem owner, Action<DB_Parameters> callback)
	{
		return (DB_Parameters) MetaDefault.NewEntity(owner, new BGMetaEntity.NewEntityContext(entity => callback((DB_Parameters)entity)));
	}
}

public partial class DB_ConsumeItem : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_ConsumeItem(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_ConsumeItem(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4700276930833097179UL,17831515632546191266UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String f_name
	{
		get => _f_name[Index];
		set => _f_name[Index] = value;
	}
	public System.Int32 f_ID
	{
		get => _f_ID[Index];
		set => _f_ID[Index] = value;
	}
	public System.String f_Image
	{
		get => _f_Image[Index];
		set => _f_Image[Index] = value;
	}
	public System.String f_Name
	{
		get => _f_Name[Index];
		set => _f_Name[Index] = value;
	}
	public Inventory.Model.ItemSO.ItemType f_Type
	{
		get => (Inventory.Model.ItemSO.ItemType) _f_Type[Index];
		set => _f_Type[Index] = value;
	}
	public ColorPallete.ItemQuality f_Quality
	{
		get => (ColorPallete.ItemQuality) _f_Quality[Index];
		set => _f_Quality[Index] = value;
	}
	public System.String f_Description
	{
		get => _f_Description[Index];
		set => _f_Description[Index] = value;
	}
	public List<DB_Modifiers> f_Modifiers => BGCodeGenUtils.GetNested<DB_Modifiers>(_f_Modifiers, Index);
	public List<DB_BuffModifier> f_BuffModifier => BGCodeGenUtils.GetNested<DB_BuffModifier>(_f_BuffModifier, Index);
	public System.Single f_Cooltime
	{
		get => _f_Cooltime[Index];
		set => _f_Cooltime[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4849060535327810088UL, 14969811644969943175UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_f_ID;
	public static BansheeGz.BGDatabase.BGFieldInt _f_ID => _ufle12jhs77_f_ID ?? (_ufle12jhs77_f_ID = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5616331167748681906UL, 369093687429684881UL), () => _ufle12jhs77_f_ID = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_Image;
	public static BansheeGz.BGDatabase.BGFieldString _f_Image => _ufle12jhs77_f_Image ?? (_ufle12jhs77_f_Image = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5351426992568603324UL, 17501226595307626138UL), () => _ufle12jhs77_f_Image = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_Name;
	public static BansheeGz.BGDatabase.BGFieldString _f_Name => _ufle12jhs77_f_Name ?? (_ufle12jhs77_f_Name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4821593479639386622UL, 17064202619032265378UL), () => _ufle12jhs77_f_Name = null));
	private static BansheeGz.BGDatabase.BGFieldEnum _ufle12jhs77_f_Type;
	public static BansheeGz.BGDatabase.BGFieldEnum _f_Type => _ufle12jhs77_f_Type ?? (_ufle12jhs77_f_Type = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEnum>(MetaDefault, new BGId(5242673092976191636UL, 2145715684539092613UL), () => _ufle12jhs77_f_Type = null));
	private static BansheeGz.BGDatabase.BGFieldEnum _ufle12jhs77_f_Quality;
	public static BansheeGz.BGDatabase.BGFieldEnum _f_Quality => _ufle12jhs77_f_Quality ?? (_ufle12jhs77_f_Quality = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEnum>(MetaDefault, new BGId(5020317818545479926UL, 15493650164768662156UL), () => _ufle12jhs77_f_Quality = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_Description;
	public static BansheeGz.BGDatabase.BGFieldString _f_Description => _ufle12jhs77_f_Description ?? (_ufle12jhs77_f_Description = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4742042642059504716UL, 18443537573339164066UL), () => _ufle12jhs77_f_Description = null));
	private static BansheeGz.BGDatabase.BGFieldNested _ufle12jhs77_f_Modifiers;
	public static BansheeGz.BGDatabase.BGFieldNested _f_Modifiers => _ufle12jhs77_f_Modifiers ?? (_ufle12jhs77_f_Modifiers = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldNested>(MetaDefault, new BGId(5125662717780029914UL, 14572246675050974607UL), () => _ufle12jhs77_f_Modifiers = null));
	private static BansheeGz.BGDatabase.BGFieldNested _ufle12jhs77_f_BuffModifier;
	public static BansheeGz.BGDatabase.BGFieldNested _f_BuffModifier => _ufle12jhs77_f_BuffModifier ?? (_ufle12jhs77_f_BuffModifier = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldNested>(MetaDefault, new BGId(4696687125843396272UL, 14995522585592437913UL), () => _ufle12jhs77_f_BuffModifier = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_f_Cooltime;
	public static BansheeGz.BGDatabase.BGFieldFloat _f_Cooltime => _ufle12jhs77_f_Cooltime ?? (_ufle12jhs77_f_Cooltime = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(4926171626812573741UL, 14612924733565722795UL), () => _ufle12jhs77_f_Cooltime = null));
	private static readonly DB_EquipItem.Factory _factory0_PFS = new DB_EquipItem.Factory();
	private static readonly DB_Parameters.Factory _factory1_PFS = new DB_Parameters.Factory();
	private static readonly DB_ConsumeItem.Factory _factory2_PFS = new DB_ConsumeItem.Factory();
	private static readonly DB_Modifiers.Factory _factory3_PFS = new DB_Modifiers.Factory();
	private static readonly DB_UpgradeItem.Factory _factory4_PFS = new DB_UpgradeItem.Factory();
	private static readonly DB_UParameters.Factory _factory5_PFS = new DB_UParameters.Factory();
	private static readonly DB_BuffModifier.Factory _factory6_PFS = new DB_BuffModifier.Factory();
	private DB_ConsumeItem() : base(MetaDefault)
	{
	}
	private DB_ConsumeItem(BGId id) : base(MetaDefault, id)
	{
	}
	private DB_ConsumeItem(BGMetaEntity meta) : base(meta)
	{
	}
	private DB_ConsumeItem(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static DB_ConsumeItem FindEntity(Predicate<DB_ConsumeItem> filter)
	{
		return MetaDefault.FindEntity(entity => filter==null || filter((DB_ConsumeItem) entity)) as DB_ConsumeItem;
	}
	public static List<DB_ConsumeItem> FindEntities(Predicate<DB_ConsumeItem> filter, List<DB_ConsumeItem> result=null, Comparison<DB_ConsumeItem> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_ConsumeItem> action, Predicate<DB_ConsumeItem> filter=null, Comparison<DB_ConsumeItem> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((DB_ConsumeItem) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((DB_ConsumeItem) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((DB_ConsumeItem)e1,(DB_ConsumeItem)e2));
	}
	public static DB_ConsumeItem GetEntity(BGId entityId) => (DB_ConsumeItem) MetaDefault.GetEntity(entityId);
	public static DB_ConsumeItem GetEntity(int index) => (DB_ConsumeItem) MetaDefault[index];
	public static DB_ConsumeItem GetEntity(string entityName) => (DB_ConsumeItem) MetaDefault.GetEntity(entityName);
	public static DB_ConsumeItem NewEntity() => (DB_ConsumeItem) MetaDefault.NewEntity();
	public static DB_ConsumeItem NewEntity(BGId entityId) => (DB_ConsumeItem) MetaDefault.NewEntity(entityId);
	public static DB_ConsumeItem NewEntity(Action<DB_ConsumeItem> callback)
	{
		return (DB_ConsumeItem) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((DB_ConsumeItem)entity)));
	}
}

public partial class DB_Modifiers : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_Modifiers(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_Modifiers(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaNested _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaNested MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaNested>(new BGId(5759291999287320189UL,8593192556327938458UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String f_name
	{
		get => _f_name[Index];
		set => _f_name[Index] = value;
	}
	public DB_ConsumeItem f_ConsumeItem
	{
		get => (DB_ConsumeItem) _f_ConsumeItem[Index];
		set => _f_ConsumeItem[Index] = value;
	}
	public System.String f_Modifier
	{
		get => _f_Modifier[Index];
		set => _f_Modifier[Index] = value;
	}
	public System.Int32 f_Value
	{
		get => _f_Value[Index];
		set => _f_Value[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4791326883080331285UL, 16020650987563054220UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_ConsumeItem;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_ConsumeItem => _ufle12jhs77_f_ConsumeItem ?? (_ufle12jhs77_f_ConsumeItem = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(4934624028187648800UL, 12510694118486198671UL), () => _ufle12jhs77_f_ConsumeItem = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_Modifier;
	public static BansheeGz.BGDatabase.BGFieldString _f_Modifier => _ufle12jhs77_f_Modifier ?? (_ufle12jhs77_f_Modifier = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4981987529764665337UL, 3383002801284849593UL), () => _ufle12jhs77_f_Modifier = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_f_Value;
	public static BansheeGz.BGDatabase.BGFieldInt _f_Value => _ufle12jhs77_f_Value ?? (_ufle12jhs77_f_Value = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5258966284076580453UL, 9197017191369534592UL), () => _ufle12jhs77_f_Value = null));
	private static readonly DB_EquipItem.Factory _factory0_PFS = new DB_EquipItem.Factory();
	private static readonly DB_Parameters.Factory _factory1_PFS = new DB_Parameters.Factory();
	private static readonly DB_ConsumeItem.Factory _factory2_PFS = new DB_ConsumeItem.Factory();
	private static readonly DB_Modifiers.Factory _factory3_PFS = new DB_Modifiers.Factory();
	private static readonly DB_UpgradeItem.Factory _factory4_PFS = new DB_UpgradeItem.Factory();
	private static readonly DB_UParameters.Factory _factory5_PFS = new DB_UParameters.Factory();
	private static readonly DB_BuffModifier.Factory _factory6_PFS = new DB_BuffModifier.Factory();
	private DB_Modifiers() : base(MetaDefault)
	{
	}
	private DB_Modifiers(BGId id) : base(MetaDefault, id)
	{
	}
	private DB_Modifiers(BGMetaEntity meta) : base(meta)
	{
	}
	private DB_Modifiers(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static DB_Modifiers FindEntity(Predicate<DB_Modifiers> filter)
	{
		return MetaDefault.FindEntity(entity => filter==null || filter((DB_Modifiers) entity)) as DB_Modifiers;
	}
	public static List<DB_Modifiers> FindEntities(Predicate<DB_Modifiers> filter, List<DB_Modifiers> result=null, Comparison<DB_Modifiers> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_Modifiers> action, Predicate<DB_Modifiers> filter=null, Comparison<DB_Modifiers> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((DB_Modifiers) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((DB_Modifiers) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((DB_Modifiers)e1,(DB_Modifiers)e2));
	}
	public static DB_Modifiers GetEntity(BGId entityId) => (DB_Modifiers) MetaDefault.GetEntity(entityId);
	public static DB_Modifiers GetEntity(int index) => (DB_Modifiers) MetaDefault[index];
	public static DB_Modifiers GetEntity(string entityName) => (DB_Modifiers) MetaDefault.GetEntity(entityName);
	public static DB_Modifiers NewEntity() => (DB_Modifiers) MetaDefault.NewEntity();
	public static DB_Modifiers NewEntity(BGId entityId) => (DB_Modifiers) MetaDefault.NewEntity(entityId);
	public static DB_Modifiers NewEntity(Action<DB_Modifiers> callback)
	{
		return (DB_Modifiers) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((DB_Modifiers)entity)));
	}
	public static DB_Modifiers NewEntity(DB_ConsumeItem owner) => (DB_Modifiers) MetaDefault.NewEntity(owner);
	public static DB_Modifiers NewEntity(DB_ConsumeItem owner, BGId entityId) => (DB_Modifiers) MetaDefault.NewEntity(owner, entityId);
	public static DB_Modifiers NewEntity(DB_ConsumeItem owner, Action<DB_Modifiers> callback)
	{
		return (DB_Modifiers) MetaDefault.NewEntity(owner, new BGMetaEntity.NewEntityContext(entity => callback((DB_Modifiers)entity)));
	}
}

public partial class DB_UpgradeItem : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_UpgradeItem(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_UpgradeItem(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4881696121040023640UL,11445211804602717835UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String f_name
	{
		get => _f_name[Index];
		set => _f_name[Index] = value;
	}
	public System.Int32 f_ID
	{
		get => _f_ID[Index];
		set => _f_ID[Index] = value;
	}
	public System.String f_Image
	{
		get => _f_Image[Index];
		set => _f_Image[Index] = value;
	}
	public System.String f_Name
	{
		get => _f_Name[Index];
		set => _f_Name[Index] = value;
	}
	public Inventory.Model.ItemSO.ItemType f_Type
	{
		get => (Inventory.Model.ItemSO.ItemType) _f_Type[Index];
		set => _f_Type[Index] = value;
	}
	public ColorPallete.ItemQuality f_Quality
	{
		get => (ColorPallete.ItemQuality) _f_Quality[Index];
		set => _f_Quality[Index] = value;
	}
	public System.String f_Description
	{
		get => _f_Description[Index];
		set => _f_Description[Index] = value;
	}
	public Inventory.Model.UpgradeItemSO.UpgradeType f_UpgradeType
	{
		get => (Inventory.Model.UpgradeItemSO.UpgradeType) _f_UpgradeType[Index];
		set => _f_UpgradeType[Index] = value;
	}
	public System.Single f_UpgradeRate
	{
		get => _f_UpgradeRate[Index];
		set => _f_UpgradeRate[Index] = value;
	}
	public List<DB_UParameters> f_UParameters => BGCodeGenUtils.GetNested<DB_UParameters>(_f_UParameters, Index);
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4848408440282556130UL, 5549940752299082161UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_f_ID;
	public static BansheeGz.BGDatabase.BGFieldInt _f_ID => _ufle12jhs77_f_ID ?? (_ufle12jhs77_f_ID = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5364706932641519508UL, 13772344173885427872UL), () => _ufle12jhs77_f_ID = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_Image;
	public static BansheeGz.BGDatabase.BGFieldString _f_Image => _ufle12jhs77_f_Image ?? (_ufle12jhs77_f_Image = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4694849433240233187UL, 11825514164417081525UL), () => _ufle12jhs77_f_Image = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_Name;
	public static BansheeGz.BGDatabase.BGFieldString _f_Name => _ufle12jhs77_f_Name ?? (_ufle12jhs77_f_Name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5381919640074103447UL, 1945428715472776376UL), () => _ufle12jhs77_f_Name = null));
	private static BansheeGz.BGDatabase.BGFieldEnum _ufle12jhs77_f_Type;
	public static BansheeGz.BGDatabase.BGFieldEnum _f_Type => _ufle12jhs77_f_Type ?? (_ufle12jhs77_f_Type = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEnum>(MetaDefault, new BGId(5401886081841782295UL, 3112386677097242791UL), () => _ufle12jhs77_f_Type = null));
	private static BansheeGz.BGDatabase.BGFieldEnum _ufle12jhs77_f_Quality;
	public static BansheeGz.BGDatabase.BGFieldEnum _f_Quality => _ufle12jhs77_f_Quality ?? (_ufle12jhs77_f_Quality = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEnum>(MetaDefault, new BGId(5591364292273270149UL, 8977164414117967509UL), () => _ufle12jhs77_f_Quality = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_Description;
	public static BansheeGz.BGDatabase.BGFieldString _f_Description => _ufle12jhs77_f_Description ?? (_ufle12jhs77_f_Description = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4633443176165630650UL, 12710068585848118409UL), () => _ufle12jhs77_f_Description = null));
	private static BansheeGz.BGDatabase.BGFieldEnum _ufle12jhs77_f_UpgradeType;
	public static BansheeGz.BGDatabase.BGFieldEnum _f_UpgradeType => _ufle12jhs77_f_UpgradeType ?? (_ufle12jhs77_f_UpgradeType = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEnum>(MetaDefault, new BGId(5681881384962623929UL, 11484005625970283146UL), () => _ufle12jhs77_f_UpgradeType = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_f_UpgradeRate;
	public static BansheeGz.BGDatabase.BGFieldFloat _f_UpgradeRate => _ufle12jhs77_f_UpgradeRate ?? (_ufle12jhs77_f_UpgradeRate = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5223239475609461533UL, 13455652467350827183UL), () => _ufle12jhs77_f_UpgradeRate = null));
	private static BansheeGz.BGDatabase.BGFieldNested _ufle12jhs77_f_UParameters;
	public static BansheeGz.BGDatabase.BGFieldNested _f_UParameters => _ufle12jhs77_f_UParameters ?? (_ufle12jhs77_f_UParameters = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldNested>(MetaDefault, new BGId(5395794530857657303UL, 7108919172277472693UL), () => _ufle12jhs77_f_UParameters = null));
	private static readonly DB_EquipItem.Factory _factory0_PFS = new DB_EquipItem.Factory();
	private static readonly DB_Parameters.Factory _factory1_PFS = new DB_Parameters.Factory();
	private static readonly DB_ConsumeItem.Factory _factory2_PFS = new DB_ConsumeItem.Factory();
	private static readonly DB_Modifiers.Factory _factory3_PFS = new DB_Modifiers.Factory();
	private static readonly DB_UpgradeItem.Factory _factory4_PFS = new DB_UpgradeItem.Factory();
	private static readonly DB_UParameters.Factory _factory5_PFS = new DB_UParameters.Factory();
	private static readonly DB_BuffModifier.Factory _factory6_PFS = new DB_BuffModifier.Factory();
	private DB_UpgradeItem() : base(MetaDefault)
	{
	}
	private DB_UpgradeItem(BGId id) : base(MetaDefault, id)
	{
	}
	private DB_UpgradeItem(BGMetaEntity meta) : base(meta)
	{
	}
	private DB_UpgradeItem(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static DB_UpgradeItem FindEntity(Predicate<DB_UpgradeItem> filter)
	{
		return MetaDefault.FindEntity(entity => filter==null || filter((DB_UpgradeItem) entity)) as DB_UpgradeItem;
	}
	public static List<DB_UpgradeItem> FindEntities(Predicate<DB_UpgradeItem> filter, List<DB_UpgradeItem> result=null, Comparison<DB_UpgradeItem> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_UpgradeItem> action, Predicate<DB_UpgradeItem> filter=null, Comparison<DB_UpgradeItem> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((DB_UpgradeItem) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((DB_UpgradeItem) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((DB_UpgradeItem)e1,(DB_UpgradeItem)e2));
	}
	public static DB_UpgradeItem GetEntity(BGId entityId) => (DB_UpgradeItem) MetaDefault.GetEntity(entityId);
	public static DB_UpgradeItem GetEntity(int index) => (DB_UpgradeItem) MetaDefault[index];
	public static DB_UpgradeItem GetEntity(string entityName) => (DB_UpgradeItem) MetaDefault.GetEntity(entityName);
	public static DB_UpgradeItem NewEntity() => (DB_UpgradeItem) MetaDefault.NewEntity();
	public static DB_UpgradeItem NewEntity(BGId entityId) => (DB_UpgradeItem) MetaDefault.NewEntity(entityId);
	public static DB_UpgradeItem NewEntity(Action<DB_UpgradeItem> callback)
	{
		return (DB_UpgradeItem) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((DB_UpgradeItem)entity)));
	}
}

public partial class DB_UParameters : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_UParameters(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_UParameters(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaNested _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaNested MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaNested>(new BGId(4934183654093906456UL,2904020752621704093UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String f_name
	{
		get => _f_name[Index];
		set => _f_name[Index] = value;
	}
	public DB_UpgradeItem f_UpgradeItem
	{
		get => (DB_UpgradeItem) _f_UpgradeItem[Index];
		set => _f_UpgradeItem[Index] = value;
	}
	public System.String f_Parameter
	{
		get => _f_Parameter[Index];
		set => _f_Parameter[Index] = value;
	}
	public System.Single f_Value
	{
		get => _f_Value[Index];
		set => _f_Value[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4827178329018747716UL, 14243508112558122902UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_UpgradeItem;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_UpgradeItem => _ufle12jhs77_f_UpgradeItem ?? (_ufle12jhs77_f_UpgradeItem = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5250727020267893100UL, 17476265273858450107UL), () => _ufle12jhs77_f_UpgradeItem = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_Parameter;
	public static BansheeGz.BGDatabase.BGFieldString _f_Parameter => _ufle12jhs77_f_Parameter ?? (_ufle12jhs77_f_Parameter = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5757939179479539111UL, 7666649010094685370UL), () => _ufle12jhs77_f_Parameter = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_f_Value;
	public static BansheeGz.BGDatabase.BGFieldFloat _f_Value => _ufle12jhs77_f_Value ?? (_ufle12jhs77_f_Value = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5134689326897069357UL, 6453831049745661320UL), () => _ufle12jhs77_f_Value = null));
	private static readonly DB_EquipItem.Factory _factory0_PFS = new DB_EquipItem.Factory();
	private static readonly DB_Parameters.Factory _factory1_PFS = new DB_Parameters.Factory();
	private static readonly DB_ConsumeItem.Factory _factory2_PFS = new DB_ConsumeItem.Factory();
	private static readonly DB_Modifiers.Factory _factory3_PFS = new DB_Modifiers.Factory();
	private static readonly DB_UpgradeItem.Factory _factory4_PFS = new DB_UpgradeItem.Factory();
	private static readonly DB_UParameters.Factory _factory5_PFS = new DB_UParameters.Factory();
	private static readonly DB_BuffModifier.Factory _factory6_PFS = new DB_BuffModifier.Factory();
	private DB_UParameters() : base(MetaDefault)
	{
	}
	private DB_UParameters(BGId id) : base(MetaDefault, id)
	{
	}
	private DB_UParameters(BGMetaEntity meta) : base(meta)
	{
	}
	private DB_UParameters(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static DB_UParameters FindEntity(Predicate<DB_UParameters> filter)
	{
		return MetaDefault.FindEntity(entity => filter==null || filter((DB_UParameters) entity)) as DB_UParameters;
	}
	public static List<DB_UParameters> FindEntities(Predicate<DB_UParameters> filter, List<DB_UParameters> result=null, Comparison<DB_UParameters> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_UParameters> action, Predicate<DB_UParameters> filter=null, Comparison<DB_UParameters> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((DB_UParameters) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((DB_UParameters) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((DB_UParameters)e1,(DB_UParameters)e2));
	}
	public static DB_UParameters GetEntity(BGId entityId) => (DB_UParameters) MetaDefault.GetEntity(entityId);
	public static DB_UParameters GetEntity(int index) => (DB_UParameters) MetaDefault[index];
	public static DB_UParameters GetEntity(string entityName) => (DB_UParameters) MetaDefault.GetEntity(entityName);
	public static DB_UParameters NewEntity() => (DB_UParameters) MetaDefault.NewEntity();
	public static DB_UParameters NewEntity(BGId entityId) => (DB_UParameters) MetaDefault.NewEntity(entityId);
	public static DB_UParameters NewEntity(Action<DB_UParameters> callback)
	{
		return (DB_UParameters) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((DB_UParameters)entity)));
	}
	public static DB_UParameters NewEntity(DB_UpgradeItem owner) => (DB_UParameters) MetaDefault.NewEntity(owner);
	public static DB_UParameters NewEntity(DB_UpgradeItem owner, BGId entityId) => (DB_UParameters) MetaDefault.NewEntity(owner, entityId);
	public static DB_UParameters NewEntity(DB_UpgradeItem owner, Action<DB_UParameters> callback)
	{
		return (DB_UParameters) MetaDefault.NewEntity(owner, new BGMetaEntity.NewEntityContext(entity => callback((DB_UParameters)entity)));
	}
}

public partial class DB_BuffModifier : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_BuffModifier(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_BuffModifier(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaNested _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaNested MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaNested>(new BGId(5178329061113589892UL,1893494159142131584UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String f_name
	{
		get => _f_name[Index];
		set => _f_name[Index] = value;
	}
	public DB_ConsumeItem f_ConsumeItem
	{
		get => (DB_ConsumeItem) _f_ConsumeItem[Index];
		set => _f_ConsumeItem[Index] = value;
	}
	public System.String f_Buff
	{
		get => _f_Buff[Index];
		set => _f_Buff[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5244398096802308222UL, 5861094624069694365UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_ConsumeItem;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_ConsumeItem => _ufle12jhs77_f_ConsumeItem ?? (_ufle12jhs77_f_ConsumeItem = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5581909377540128126UL, 1327729893800708745UL), () => _ufle12jhs77_f_ConsumeItem = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_Buff;
	public static BansheeGz.BGDatabase.BGFieldString _f_Buff => _ufle12jhs77_f_Buff ?? (_ufle12jhs77_f_Buff = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5152382962319305051UL, 12730476627654030505UL), () => _ufle12jhs77_f_Buff = null));
	private static readonly DB_EquipItem.Factory _factory0_PFS = new DB_EquipItem.Factory();
	private static readonly DB_Parameters.Factory _factory1_PFS = new DB_Parameters.Factory();
	private static readonly DB_ConsumeItem.Factory _factory2_PFS = new DB_ConsumeItem.Factory();
	private static readonly DB_Modifiers.Factory _factory3_PFS = new DB_Modifiers.Factory();
	private static readonly DB_UpgradeItem.Factory _factory4_PFS = new DB_UpgradeItem.Factory();
	private static readonly DB_UParameters.Factory _factory5_PFS = new DB_UParameters.Factory();
	private static readonly DB_BuffModifier.Factory _factory6_PFS = new DB_BuffModifier.Factory();
	private DB_BuffModifier() : base(MetaDefault)
	{
	}
	private DB_BuffModifier(BGId id) : base(MetaDefault, id)
	{
	}
	private DB_BuffModifier(BGMetaEntity meta) : base(meta)
	{
	}
	private DB_BuffModifier(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static DB_BuffModifier FindEntity(Predicate<DB_BuffModifier> filter)
	{
		return MetaDefault.FindEntity(entity => filter==null || filter((DB_BuffModifier) entity)) as DB_BuffModifier;
	}
	public static List<DB_BuffModifier> FindEntities(Predicate<DB_BuffModifier> filter, List<DB_BuffModifier> result=null, Comparison<DB_BuffModifier> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_BuffModifier> action, Predicate<DB_BuffModifier> filter=null, Comparison<DB_BuffModifier> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((DB_BuffModifier) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((DB_BuffModifier) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((DB_BuffModifier)e1,(DB_BuffModifier)e2));
	}
	public static DB_BuffModifier GetEntity(BGId entityId) => (DB_BuffModifier) MetaDefault.GetEntity(entityId);
	public static DB_BuffModifier GetEntity(int index) => (DB_BuffModifier) MetaDefault[index];
	public static DB_BuffModifier GetEntity(string entityName) => (DB_BuffModifier) MetaDefault.GetEntity(entityName);
	public static DB_BuffModifier NewEntity() => (DB_BuffModifier) MetaDefault.NewEntity();
	public static DB_BuffModifier NewEntity(BGId entityId) => (DB_BuffModifier) MetaDefault.NewEntity(entityId);
	public static DB_BuffModifier NewEntity(Action<DB_BuffModifier> callback)
	{
		return (DB_BuffModifier) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((DB_BuffModifier)entity)));
	}
	public static DB_BuffModifier NewEntity(DB_ConsumeItem owner) => (DB_BuffModifier) MetaDefault.NewEntity(owner);
	public static DB_BuffModifier NewEntity(DB_ConsumeItem owner, BGId entityId) => (DB_BuffModifier) MetaDefault.NewEntity(owner, entityId);
	public static DB_BuffModifier NewEntity(DB_ConsumeItem owner, Action<DB_BuffModifier> callback)
	{
		return (DB_BuffModifier) MetaDefault.NewEntity(owner, new BGMetaEntity.NewEntityContext(entity => callback((DB_BuffModifier)entity)));
	}
}
#pragma warning restore 414
